version: '3.1'

services:

  db:
    image: postgres:12-alpine
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
