name: Application Test and Deploy
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: OTP ${{ matrix.otp }} | Elixir ${{ matrix.elixir }} | Node ${{ matrix.node }} | OS ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        otp: [22.2.4]
        elixir: [1.10.0]
        node: [12.x]

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options:
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: phoenixcicd_dev

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.2.4
          elixir-version: 1.10.0
      - run: mix deps.get
      - run: mix test

  deploy:
    runs-on: ubuntu-latest
    steps:
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: ${{ github.repository }}
      if: github.ref == 'refs/heads/master'
      run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
